using Microsoft.AspNetCore.Identity;

namespace OnlineShop.Domain.Auth
{
    /// <summary>
    /// Gets or sets the DbSet<TEntity> of User tokens.
    /// </summary>
    public class UserToken : IdentityUserToken<int>
    {
    }
}

/// <summary>
/// User tokens are security tokens that are used to represent 
/// a user's identity in an application. They are generated by 
/// an authentication system and contain information about the 
/// user, such as their username, claims, and other relevant information.
/// </summary>
